version: 2.1
#type of executor (windows, macos, docker, machine)
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: blvck49/build-01
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker 
      - run:
          name: Build Docker image
          command: | 
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME 
      - persist_to_workspace:
          root: .
          paths:
          - ./image.tar
  deploy:
    executor: docker-publisher
    steps:
      - checkout
      - run:
          name: Deploy main to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git.main
  publish-latest:
    executor: docker-publisher
    steps:
       - attach_workspace:
            at: /tmp/workspace
       - setup_remote_docker
       - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
       - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" 
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: main
